<a href="https://colab.research.google.com/github/mohitgoyal1409/NLP/blob/main/nlp1/5_text_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

temp_df = pd.read_csv('IMDB Dataset.csv')

df = temp_df.iloc[:10000]

df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
df['sentiment'].value_counts()
df.isnull().sum()
df.duplicated().sum()

np.int64(17)

In [ ]:

df.drop_duplicates(inplace=True)

/tmp/ipykernel_8315/550979338.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)

In [ ]:
# Basic Preprocessing
# Remove tags
# Lowercase
# remove stopwords

import re
def remove_tags(raw_text):
      cleaned_text = re.sub(re.compile(' <.*? >'), '', raw_text)
      return cleaned_text

In [ ]:
df['review'] = df['review' ].apply(remove_tags)

/tmp/ipykernel_8315/3586035928.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review' ].apply(remove_tags)

In [ ]:
df['review'] = df['review'].apply(lambda x:x. lower())

/tmp/ipykernel_8315/836025102.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lambda x:x. lower())

In [ ]:
import nltk
from nltk. corpus import stopwords
nltk.download('stopwords')
sw_list = stopwords.words('english')
df['review'] = df['review' ].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
/tmp/ipykernel_8315/856866198.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review' ].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

In [ ]:
X = df.iloc[:,0:1]
y = df['sentiment' ]

In [ ]:
X

                                                 review
0     one reviewers mentioned watching 1 oz episode ...
1     wonderful little production. <br /><br />the f...
2     thought wonderful way spend time hot summer we...
3     basically there's family little boy (jake) thi...
4     petter mattei's "love time money" visually stu...
...                                                 ...
9995  fun, entertaining movie wwii german spy (julie...
9996  give break. anyone say "good hockey movie"? kn...
9997  movie bad movie. watching endless series bad h...
9998  movie probably made entertain middle school, e...
9999  smashing film film-making. shows intense stran...

[9983 rows x 1 columns]

In [ ]:
y

0       positive
1       positive
2       positive
3       negative
4       positive
          ...
9995    positive
9996    negative
9997    negative
9998    negative
9999    positive
Name: sentiment, Length: 9983, dtype: object

In [ ]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

y = encoder.fit_transform(y)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=1)

In [ ]:
# Applying BoW

from sklearn.feature_extraction. text import CountVectorizer

cv = CountVectorizer()

X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review' ]).toarray()

In [ ]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

gnb.fit(X_train_bow,y_train)

GaussianNB()

In [ ]:
y_pred = gnb.predict(X_test_bow)

from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(y_test, y_pred)

0.6349524286429644

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test, y_pred)

0.8397596394591887

In [ ]:
CV = CountVectorizer(ngram_range=(1,2))

X_train_bow = cv.fit_transform(X_train['review' ]).toarray()
X_test_bow = cv.transform(X_test['review' ]). toarray()

rf = RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test, y_pred)

0.8372558838257386

In [ ]:
from sklearn. feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

X_train_tfidf = tfidf. fit_transform(X_train['review' ]). toarray()
X_test_tfidf = tfidf. transform(X_test['review' ])

rf = RandomForestClassifier()

rf.fit(X_train_tfidf,y_train)
y_pred = rf.predict(X_test_tfidf)

accuracy_score(y_test, y_pred)

0.8472709063595393

In [ ]:
!pip install gensim

Collecting gensim
  Downloading gensim-4.4.0-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.13/dist-packages (from gensim) (2.1.3)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.13/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.13/dist-packages (from gensim) (8.0.2)
Requirement already satisfied: wrapt in /usr/local/lib/python3.13/dist-packages (from smart_open>=1.8.1->gensim) (2.5.0)
Downloading gensim-4.4.0-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.8/27.8 MB 29.7 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [ ]:
import gensim
import nltk
nltk.download('punkt_tab')

from nltk import sent_tokenize
from gensim.utils import simple_preprocess

story = []
for doc in df['review']:
    raw_sent = sent_tokenize(doc)
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

model= gensim.models.Word2Vec(
window=10,
min_count=2
)

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [ ]:
model.build_vocab(story)

model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

len(model.wv.index_to_key)

def document_vector(doc):
      # remove out-of-vocabulary words
      doc = [word for word in doc.split() if word in model.wv.index_to_key]
      return np.mean(model.wv[doc], axis=0)

document_vector(df['review'].values [0])

array([-2.15388387e-01,  1.99845061e-01,  2.00019047e-01,  2.16761485e-01,
        3.62546593e-02, -5.26039004e-01,  8.46793279e-02,  7.39330411e-01,
       -2.09416360e-01, -2.71681380e-02, -1.29907921e-01, -6.26033485e-01,
       -1.09893426e-01,  3.39213818e-01,  1.79701045e-01, -2.46835247e-01,
        1.39239326e-01, -2.18697727e-01, -4.34406362e-02, -9.19378698e-01,
        8.88438746e-02,  1.36184305e-01,  2.33828247e-01, -3.18664238e-02,
        9.40774083e-02,  1.76118072e-02, -3.51211667e-01, -1.67298153e-01,
       -3.53907585e-01, -1.71614587e-01,  4.71244574e-01, -2.93457955e-02,
        2.70513505e-01, -3.02405000e-01,  3.98803651e-02,  4.70060378e-01,
        3.35366651e-02, -3.96562457e-01, -3.15142661e-01, -4.58791286e-01,
        7.96989873e-02, -4.42876458e-01, -1.94173098e-01, -1.49397529e-04,
        1.15761325e-01, -2.75728703e-01, -2.13099703e-01,  4.40485813e-02,
        4.19989198e-01,  3.68296742e-01,  1.27577320e-01, -3.17850471e-01,
       -1.40244901e-01,  5.89122362e-02, -8.86467621e-02,  3.20682883e-01,
        1.57742634e-01, -1.71489254e-01, -3.21087122e-01,  1.46258965e-01,
       -1.33506864e-01,  6.67791143e-02, -1.27045318e-01, -2.28075534e-02,
       -4.97733861e-01,  3.97003114e-01,  1.65085405e-01,  4.36875463e-01,
       -2.33421668e-01,  3.56367201e-01,  3.31885219e-02,  1.06662013e-01,
        3.63362759e-01, -2.09006190e-01,  2.25751966e-01,  9.43497047e-02,
        8.01560804e-02, -3.89348626e-01, -2.99005240e-01,  1.13946281e-01,
       -1.92637876e-01, -1.12276740e-01, -4.31692302e-01,  5.06097615e-01,
       -1.13446184e-01,  1.91189781e-01,  5.64345233e-02,  2.27468714e-01,
        5.25378168e-01,  3.66961360e-01,  3.23877275e-01,  1.15124471e-01,
       -1.24863766e-01,  1.22944392e-01,  5.85113049e-01,  3.68835419e-01,
        8.54303315e-02, -2.56115288e-01,  8.82395953e-02,  1.97414488e-01],
      dtype=float32)

In [ ]:
from tqdm import tqdm

X = []
for doc in tqdm(df['review' ]. values):
    X.append(document_vector(doc))

X = np.array(X)
X.shape
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

y = encoder. fit_transform(df['sentiment' ])

100%|██████████| 9983/9983 [03:47<00:00, 43.94it/s]

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=1)

from sklearn. ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

rf = RandomForestClassifier()
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test, y_pred)

0.7701552328492739